### ISSUE TITLE
Square Logo

### ISSUE THREAD

**Issue by SJrX** [systemd/brand.systemd.io#2]
The website mentions: 

> For use cases where the horizontal logo doesn't work, the vertical alternate logo can be used instead. For sizes too small for the text to be readable (e.g. avatars, icons, and the like), use the standalone logomark.

I would like to request some kind of square logo for file system and other usages.

**Comment by bertob** [comment]
The idea was that for square use cases you'd just use the logomark-only one and crop it as appropriate (since e.g. in some cases avatars are rounded). What kinds of use cases did you have in mind (not sure what you mean by "file system")?

**Comment by SJrX** [comment]
I mean a view like the following:

![image](https://user-images.githubusercontent.com/1916599/69653801-94d5d780-1028-11ea-8566-73a69901d90c.png)

Or in IntelliJ Based IDEs:

![image](https://user-images.githubusercontent.com/1916599/69653948-d49cbf00-1028-11ea-9ad6-103b42304f89.png)

I did look at the logo, but due to the spacing, I can't get something at 16x16 to look remotely good. I ended up just using the same inspiration, and made something using IntelliJ's icons.

**Comment by bertob** [comment]
I think if you want it to work at 16x16 you'll need to do something custom either way, not least because you'll want to align it to the pixel grid. I did that for the website favicon, see https://github.com/systemd/brand.systemd.io/blob/master/favicon.svg

In general, file type icons are done by apps/platforms anyway, so I don't think it would make sense to provide assets for that.
