### ISSUE TITLE
Not secure

### ISSUE THREAD

**Issue by rgherta** [systemd/brand.systemd.io#5]
brand.systemd.io is using a certificate issued for github therefore rending it Not Secure

**Comment by keszybz** [comment]
@poettering:
```console
$  dig brand.systemd.io +nostats +nocomments +nocmd
;brand.systemd.io.		IN	A
brand.systemd.io.	318	IN	CNAME	systemd.io.
...
```

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain says that this should point to `systemd.github.io` instead.

We should be able to enable https then.

**Comment by bnf** [comment]
Can confirm. It seems Github doesn't try to acquire a https certificate when a `CNAME` is used but that doesn't match `{org}.github.io` – it allows explicit A records instead of CNAME for top-level domain usage, but not invalid CNAMEs.

Confirmed that in context of https://github.com/systemd/brand.systemd.io/issues/4 by also using `CNAME systemd.io` for my preview domain.
Same issue, no HTTPS certificate was created.
Changing the CNAME to  `{org}.github.io`  and removing + re-adding [1] the domain on https://github.com/systemd/brand.systemd.io/settings/pages triggered a new certificate request by github.

So, `brand.systemd.io CNAME systemd.github.io` would fix this.

[1] https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https
> The process may take some time. If the process has not completed several minutes after you clicked Save, try clicking Remove next to your custom domain name. Retype the domain name and click Save again. This will cancel and restart the provisioning process.

**Comment by keszybz** [comment]
@poettering ^

**Comment by erikinkinen** [comment]
It seems to working now?

The certificate has a DNS Name:
brand.systemd.io

Should this be closed?

**Comment by rgherta** [comment]
Thanks
